"""Shared slash command definitions for CLI and TUI."""

SLASH_COMMANDS = [
    "/qc", "/align", "/variant-call", "/annotate", "/pipeline",
    "/blast", "/msa", "/phylo", "/summary", "/search", "/explain", "/report",
    "/lookup", "/drug", "/disease", "/literature", "/frequency", "/cancer", "/domains", "/structure",
    "/classify", "/pgx-profile", "/prioritize", "/compare",
    "/mcp", "/swarm", "/history", "/provider", "/model", "/help", "/quit",
]

COMMAND_SKILL_MAP = {
    "/qc": "sequencing/quality-control",
    "/align": "sequencing/alignment",
    "/variant-call": "sequencing/variant-calling",
    "/annotate": "sequencing/annotation",
    "/pipeline": "sequencing/pipeline",
    "/blast": "comparative/blast-analysis",
    "/msa": "comparative/multiple-alignment",
    "/phylo": "comparative/phylogenetics",
    "/summary": "exploration/sequence-summary",
    "/search": "exploration/database-search",
    "/explain": "exploration/variant-explain",
    "/report": "reporting/clinical-report",
    "/lookup": "exploration/variant-lookup",
    "/drug": "pharmacogenomics/drug-interaction",
    "/disease": "exploration/disease-association",
    "/literature": "exploration/literature-search",
    "/frequency": "exploration/population-frequency",
    "/cancer": "oncology/cancer-mutations",
    "/domains": "structural/protein-domains",
    "/structure": "structural/protein-structure",
    "/classify": "clinical/acmg-classify",
    "/pgx-profile": "pharmacogenomics/pgx-profile",
    "/prioritize": "clinical/variant-prioritize",
    "/compare": "clinical/vcf-compare",
}

COMMAND_DESCRIPTIONS = {
    "/qc": "Run quality control (FastQC)",
    "/align": "Align reads to reference genome",
    "/variant-call": "Call variants (GATK/FreeBayes)",
    "/annotate": "Annotate variants (SnpEff/VEP)",
    "/pipeline": "Full pipeline: QC → align → call → annotate",
    "/blast": "BLAST similarity search",
    "/msa": "Multiple sequence alignment",
    "/phylo": "Phylogenetic tree construction",
    "/summary": "Summarize a genomic file",
    "/search": "Query databases (NCBI, Ensembl...)",
    "/explain": "Explain a variant, gene, or region",
    "/report": "Generate clinical HTML report from VCF",
    "/lookup": "Comprehensive variant lookup (ClinVar + gnomAD + dbSNP)",
    "/drug": "Drug-gene interactions (PharmGKB)",
    "/disease": "Gene-disease associations (OMIM)",
    "/literature": "Search scientific literature (PubMed)",
    "/frequency": "Population allele frequencies (gnomAD)",
    "/cancer": "Somatic cancer mutations (COSMIC)",
    "/domains": "Protein domain annotations (InterPro)",
    "/structure": "Protein structure (AlphaFold + PDB)",
    "/classify": "ACMG/AMP variant classification",
    "/pgx-profile": "Pharmacogenomics profile from VCF",
    "/mcp": "Manage MCP servers (connect, status)",
    "/swarm": "Show background analyses",
    "/history": "Session history",
    "/provider": "Switch AI provider",
    "/model": "Switch model",
    "/help": "Show available commands",
    "/quit": "Exit genomix",
}

COMMAND_SECTIONS = [
    ("Analysis", ["/qc", "/align", "/variant-call", "/annotate", "/pipeline"]),
    ("Comparative", ["/blast", "/msa", "/phylo"]),
    ("Exploration", ["/summary", "/search", "/explain", "/lookup"]),
    ("Clinical", ["/report", "/drug", "/disease", "/frequency", "/classify", "/pgx-profile"]),
    ("Oncology", ["/cancer"]),
    ("Literature", ["/literature"]),
    ("Structural", ["/domains", "/structure"]),
    ("Session", ["/mcp", "/swarm", "/history", "/provider", "/model", "/help", "/quit"]),
]
