"""Clinical report generator — renders variant analysis as HTML."""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from html import escape as html_escape
from pathlib import Path
from typing import Any


def _safe(text: str) -> str:
    """Escape HTML to prevent XSS from LLM output."""
    return html_escape(str(text), quote=True)


def _sanitize_html(text: str) -> str:
    """Allow only safe HTML tags in interpretation/recommendation text."""
    # Remove all tags except allowed ones
    allowed_tags = r'(?:p|strong|em|ul|ol|li|div|br|span|h[1-6])'
    cleaned = re.sub(
        r'<(?!/?' + allowed_tags + r'(?:\s[^>]*)?>)(?!/' + allowed_tags + r'>)[^>]*>',
        '',
        text,
    )
    # Remove event handlers and javascript
    cleaned = re.sub(r'\s+on\w+\s*=\s*["\'][^"\']*["\']', '', cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r'javascript:', '', cleaned, flags=re.IGNORECASE)
    return cleaned


REPORT_HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Genomix Clinical Report — {title}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a2e; background: #f8f9fa; padding: 2rem; max-width: 900px; margin: 0 auto; }}
  .header {{ background: linear-gradient(135deg, #0d7377, #14919b); color: white; padding: 2rem; border-radius: 12px; margin-bottom: 2rem; }}
  .header h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
  .header .subtitle {{ opacity: 0.85; font-size: 0.95rem; }}
  .meta {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 2rem; }}
  .meta-card {{ background: white; padding: 1.2rem; border-radius: 8px; border: 1px solid #e0e0e0; }}
  .meta-card h3 {{ color: #0d7377; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.5rem; }}
  .section {{ background: white; padding: 1.5rem; border-radius: 8px; border: 1px solid #e0e0e0; margin-bottom: 1.5rem; }}
  .section h2 {{ color: #0d7377; font-size: 1.2rem; margin-bottom: 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid #e8f4f4; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
  th {{ background: #f0f7f7; color: #0d7377; text-align: left; padding: 0.7rem; font-weight: 600; }}
  td {{ padding: 0.7rem; border-bottom: 1px solid #eee; }}
  tr:hover {{ background: #f8fffe; }}
  .pathogenic {{ color: #d32f2f; font-weight: 600; }}
  .likely-pathogenic {{ color: #e64a19; font-weight: 600; }}
  .vus {{ color: #f57c00; }}
  .benign {{ color: #388e3c; }}
  .risk-factor {{ color: #7b1fa2; font-weight: 600; }}
  .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.8rem; font-weight: 600; }}
  .badge-pathogenic {{ background: #ffebee; color: #c62828; }}
  .badge-likely {{ background: #fff3e0; color: #e65100; }}
  .badge-vus {{ background: #fff8e1; color: #f57f17; }}
  .badge-benign {{ background: #e8f5e9; color: #2e7d32; }}
  .badge-risk {{ background: #f3e5f5; color: #6a1b9a; }}
  .recommendation {{ background: #e8f4f4; padding: 1rem; border-radius: 6px; border-left: 4px solid #0d7377; margin-top: 0.5rem; }}
  .footer {{ text-align: center; color: #999; font-size: 0.8rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #eee; }}
  .gene-name {{ font-weight: 700; color: #1565c0; }}
</style>
</head>
<body>
<div class="header">
  <h1>Genomix Clinical Variant Report</h1>
  <div class="subtitle">{title}</div>
</div>

<div class="meta">
  <div class="meta-card">
    <h3>Sample Information</h3>
    <p><strong>File:</strong> {filename}</p>
    <p><strong>Reference:</strong> {reference}</p>
    <p><strong>Total variants:</strong> {total_variants}</p>
  </div>
  <div class="meta-card">
    <h3>Report Details</h3>
    <p><strong>Generated:</strong> {date}</p>
    <p><strong>Tool:</strong> Genomix CLI v{version}</p>
    <p><strong>Analysis:</strong> AI-assisted variant interpretation</p>
  </div>
</div>

<div class="section">
  <h2>Variant Summary</h2>
  <table>
    <thead>
      <tr><th>Gene</th><th>Variant</th><th>Type</th><th>Zygosity</th><th>Significance</th></tr>
    </thead>
    <tbody>
      {variant_rows}
    </tbody>
  </table>
</div>

<div class="section">
  <h2>Clinical Interpretation</h2>
  {interpretation}
</div>

<div class="section">
  <h2>Recommendations</h2>
  {recommendations}
</div>

<div class="footer">
  <p>Generated by Genomix CLI — AI-powered genome analysis</p>
  <p>This report is for research purposes only. Clinical decisions should involve qualified genetic counselors.</p>
</div>
</body>
</html>'''


def _significance_badge(sig: str) -> str:
    """Convert significance to styled HTML badge."""
    sig_lower = sig.lower().replace("_", " ").replace("-", " ")
    if "pathogenic" == sig_lower:
        return f'<span class="badge badge-pathogenic">{sig}</span>'
    elif "likely pathogenic" in sig_lower:
        return f'<span class="badge badge-likely">{sig}</span>'
    elif "vus" in sig_lower or "uncertain" in sig_lower:
        return f'<span class="badge badge-vus">{sig}</span>'
    elif "benign" in sig_lower:
        return f'<span class="badge badge-benign">{sig}</span>'
    elif "risk" in sig_lower:
        return f'<span class="badge badge-risk">{sig}</span>'
    return f'<span class="badge">{sig}</span>'


def generate_report(
    filename: str,
    variants: list[dict[str, str]],
    interpretation: str,
    recommendations: str,
    reference: str = "GRCh38",
    title: str = "",
) -> str:
    """Generate an HTML clinical report from structured variant data.

    Args:
        filename: Source VCF filename
        variants: List of dicts with keys: gene, variant, type, zygosity, significance
        interpretation: HTML string of clinical interpretation
        recommendations: HTML string of recommendations
        reference: Reference genome
        title: Report title

    Returns:
        Complete HTML string
    """
    from genomix import __version__

    if not title:
        title = f"Variant Analysis — {Path(filename).stem}"

    variant_rows = ""
    for v in variants:
        sig_badge = _significance_badge(v.get("significance", "Unknown"))
        variant_rows += f"""      <tr>
        <td class="gene-name">{_safe(v.get('gene', 'Unknown'))}</td>
        <td>{_safe(v.get('variant', ''))}</td>
        <td>{_safe(v.get('type', ''))}</td>
        <td>{_safe(v.get('zygosity', ''))}</td>
        <td>{sig_badge}</td>
      </tr>\n"""

    interpretation = _sanitize_html(interpretation)
    recommendations = _sanitize_html(recommendations)

    html = REPORT_HTML_TEMPLATE.format(
        title=_safe(title),
        filename=_safe(filename),
        reference=_safe(reference),
        total_variants=len(variants),
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        version=__version__,
        variant_rows=variant_rows,
        interpretation=interpretation,
        recommendations=recommendations,
    )
    return html


def save_report(html: str, output_path: Path) -> Path:
    """Save HTML report to file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")
    return output_path
